name: release-please-pr
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: write

jobs:
  refresh-lock-and-smoke-test:
    if: startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}  # checkout the release-please PR branch

    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    # Refresh lockfile so it matches bumped version/deps in the PR
    - name: Update uv.lock
      run: |
        uv lock --upgrade
        if git diff --quiet -- uv.lock; then
          echo "No lockfile changes."
        else
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uv.lock
          git commit -m "chore: update uv.lock for release"
          git push
        fi

    # Build wheel & sdist
    - name: Build dist
      run: uv build

    # Smoke test: create venv, install wheel, import package
    - name: Install and import smoke test
      run: |
        uv venv .venv
        . .venv/bin/activate
        uv pip install dist/*.whl
        python - <<'PY'
        import sys
        print("Python:", sys.version)
        import docskin  # adjust if your import root differs
        print("Imported docskin OK")
        PY
