name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      tag_name: ${{ steps.rp.outputs.tag_name }}
    steps:
    - id: rp
      uses: googleapis/release-please-action@v4
      with:
        release-type: python
        package-name: docskin

  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.release.outputs.tag_name }}

    - name: Enable caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Build package
      run: uv build

    - name: Install and import smoke test
      run: |
        uv venv .venv
        . .venv/bin/activate
        uv pip install dist/*.whl
        python - <<'PY'
        import sys
        print("Python:", sys.version)
        import docskin  # adjust if your import root differs
        print("Imported docskin OK")
        PY

    - name: Publish to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: uv publish